<a href="https://colab.research.google.com/github/gowri862/ChatApp/blob/master/Copy_of_Welcome_To_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
text = "strings are a fundamental data type"
capitalized_text = text.capitalize()
print(capitalized_text)


Strings are a fundamental data type


In [4]:
text = "Hello World"
upper_text = text.upper()
lower_text = text.lower()
print(upper_text)  # Output: "HELLO WORLD"
print(lower_text)  # Output: "hello world"




HELLO WORLD
hello world


In [6]:
text = "   Hello, World!   "
stripped_text = text.strip()  # Removes leading/trailing spaces
print(stripped_text)  # Output: "Hello, World!"




Hello, World!


In [7]:
text = "Hello, World, World"
new_text = text.replace("World", "Python")
print(new_text)


Hello, Python, Python


In [35]:
mystr1="This is 5 days FDP program on Data"
mystr2 = 'at KG college of Arts & Science'
#capitalize
print(mystr1.capitalize())
#upper&lower
upper_text = mystr1.upper()
lower_text = mystr1.lower()
print("upper Text: ",upper_text)
print("Lower Text: ",lower_text)
#spilit
words=mystr1.split()
print("spilit method",words)
#join
joined='/'.join(mystr1)
print("joined text : ",joined)
#replace
new_text = mystr1.replace("FDP", "Faculty Development Program")
print("Replace method : ",new_text)
#starts with and ends with
starts_with_hello = mystr1.startswith("days")
ends_with_world = mystr1.endswith("python")
print("Strats with",starts_with_hello)
print("Ends with",ends_with_world)


#string concatenation
concatenated_str = mystr1 + mystr2
print(concatenated_str)
#substring
print("Substring : ",mystr1[0:7])

#length of both the original mystr1 and the sliced substring
len_mystr1 = len(mystr1)
len_substring = len(mystr1[0:7])
print("Length of mystr1:", len_mystr1)
print("Length of substring: " ,len_substring)




This is 5 days fdp program on data
upper Text:  THIS IS 5 DAYS FDP PROGRAM ON DATA
Lower Text:  this is 5 days fdp program on data
spilit method ['This', 'is', '5', 'days', 'FDP', 'program', 'on', 'Data']
joined text :  T/h/i/s/ /i/s/ /5/ /d/a/y/s/ /F/D/P/ /p/r/o/g/r/a/m/ /o/n/ /D/a/t/a
Replace method :  This is 5 days Faculty Development Program program on Data
Strats with False
Ends with False
This is 5 days FDP program on Dataat KG college of Arts & Science
Substring :  This is
Length of mystr1: 34
Length of substring:  7


In [46]:
file = open("Newone.txt", "w")
print("created")

# Writing data to the file
file.write("Hello, World!")

# Closing the file
file.close()

# Opening a file in read mode
file = open("Newone.txt", "r")

# Reading the entire content
content = file.read()
print(content)





created
Hello, World!


In [66]:
# Opening a file in append mode
file = open("sample.txt", "a")
dict={"name":"Vara","age":28}
# with open("sample.txt","w") as f:
#   f.write(str(dict))
# with open("sample.txt", "r") as f:
#     print(f.read())
# with open("sample.txt", "a+") as f:
#     f.write("Marks: 90")
#     f.seek(0)
#     print(f.read())
file = open("sample.txt", "r")
print(file.readline())
print(file.readline())
file.close()

file = open("sample.txt", "r")
data = file.readlines()
print(data)
file.close()

# Appending data to the file
# file.write("\nThis is a new line.")
# print("successfully added")
# Closing the file
file.close()


{'name': 'Vara', 'age': 28}Marks: 90

["{'name': 'Vara', 'age': 28}Marks: 90"]


In [60]:
with open("IMG_20240820_074852.jpg", "rb") as file:
    binary_data = file.read()
    print("original image fetched")

# Writing binary data to a file
with open("copy_image.jpg", "wb") as file:
    file.write(binary_data)
    print("copied successfully")


original image fetched
copied successfully


In [75]:
import csv
# Writing data to a CSV file
with open("Sample_csv.csv", "a", newline="") as csvfile:
     writer = csv.writer(csvfile)
     writer.writerow(["parabu", 100])


with open("Sample_csv.csv", "r") as file:
    print(file.read())

print("Written done")
    # csv_writer = csv.writer(csvfile)
    # csv_writer.writerow(["Name", "Age"])
    # csv_writer.writerow(["Bhaskar", 34])
    # csv_writer.writerow(["Vinoth", 34])
    # csv_writer.writerow(["Senthil", 37])
    # csv_writer.writerow(["Venkatesh", 34])


# Reading data from a CSV file
# with open("Sample_csv.csv", "r") as csvfile:
#     csv_reader = csv.reader(csvfile)
#     for row in csv_reader:
#         print(row)
#         print("done reading")



Nani,100
Gowri,80
Nilasri,90
parabu,100

Written done


In [80]:
import json
# Writing data to a JSON file
data = [{"name": "Alice", "age": 30},{"name": "Gowri", "age": 8}]
with open("data.json", "w") as jsonfile:
    json.dump(data, jsonfile)

# Reading data from a JSON file
with open("data.json", "r") as jsonfile:
    loaded_data = json.load(jsonfile)
    print(loaded_data)



[{'name': 'Alice', 'age': 30}, {'name': 'Gowri', 'age': 8}]


In [81]:
pip install numpy

In [101]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr)
# list
list1=[10,20,30]
list2 = [1,2,3]
print(list1+list2)
#array
a=np.array(list1)
b=np.array(list2)
print(a+b)

arr=np.array([10,20,30,40],[50,60,70,80])
print("Shape:", arr.shape)
print("Dimensions:", arr.ndim)
print("Size:", arr.size)
print("Data Type:", arr.dtype)


marks = np.array([100 , 70, 80, 90, 85, 75])
print("First Student:", marks[0])
print("Last Student:", marks[-1])
print("Top 3 Marks:", marks[1:4])


# marks =np.array([10,20,30],[40,50,60])
# print(marks)

SyntaxError: invalid syntax (1571514822.py, line 18)

In [98]:
import numpy as np

num = "12,25,36,78,69,45,18,27,28,42"
arr = np.array(num.split(','),dtype=int)

print(arr)
print(type(arr))


[12 25 36 78 69 45 18 27 28 42]
<class 'numpy.ndarray'>


In [102]:
data = np.array([
	[10, 20, 30],
	[40, 50, 60]
])
print(data[0, 1])
print(data[:, 1])


20
[20 50]


In [103]:
arr = np.array([10, 20, 30, 40])
print("Sum:", np.sum(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Mean:", np.mean(arr))
print("Median:",np.median(arr))
print("Standard Deviaition:",np.std(arr))


Sum: 100
Max: 40
Min: 10
Mean: 25.0
Median: 25.0
Standard Deviaition: 11.180339887498949


In [107]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(3, 2)
print(new_arr)
print(new_arr.flatten())


[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [109]:
a = np.arange(12).reshape(4, 3)
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.dtype.name)
print(a.size)
print(a.itemsize)
print(type(a))
print(type(a.dtype))
print(type(a.dtype.name))
print(np.arange(1, 10, 2))


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)
2
int64
int64
12
8
<class 'numpy.ndarray'>
<class 'numpy.dtypes.Int64DType'>
<class 'str'>
[1 3 5 7 9]


In [110]:
arr = np.array([10, 20, 30])
copy_arr = arr.copy()
view_arr = arr.view()
arr[0] = 99
print("Original:", arr)
print("Copy:", copy_arr)   # Not affected
print("View:", view_arr)   # Affected


Original: [99 20 30]
Copy: [10 20 30]
View: [99 20 30]


In [111]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(np.sum(a, axis=1))
print(np.sum(a, axis=0))


[ 6 15]
[5 7 9]


In [126]:
my_array=np.array([43,24,88,22])
# print("Max:", np.max(my_array>=50))
print("Numbers > 50 ", my_array[my_array >50])

my_array=np.array([2,3,10,5,7,1,6,4,8,9,11,23,12,0,15])
filtered_array = my_array[(my_array < 5) | (my_array > 9)]
print(filtered_array)

# Filter Values Contained in List​
#filter for values that are equal to 2, 3, 5, or 12​

target_values = [2, 3, 5, 12]
filtered_list = [x for x in my_array if x in target_values]
# print(filtered_list)
result = np.array(filtered_list)
print(result)

Numbers > 50  [88]
[ 2  3 10  1  4 11 23 12  0 15]
[ 2  3  5 12]


In [127]:
arr = np.array([5, 2, 9, 1, 7])
# Sort in descending order
sorted_desc = np.sort(arr)[::-1]
print("Original array:", arr)
print("Sorted descending:", sorted_desc)


Original array: [5 2 9 1 7]
Sorted descending: [9 7 5 2 1]


In [130]:
import numpy as np
x=np.array([[1,4,2,33],[9,13,61,1],[43,24,88,22]])
print(x)
y=np.sort(x)
print(y)
z=np.sort(x,axis=None)
print(z)
p=np.sort(x,axis=0)
print(p)
q=np.sort(x,axis=1)
print(q)



[[ 1  4  2 33]
 [ 9 13 61  1]
 [43 24 88 22]]
[[ 1  2  4 33]
 [ 1  9 13 61]
 [22 24 43 88]]
[ 1  1  2  4  9 13 22 24 33 43 61 88]
[[ 1  4  2  1]
 [ 9 13 61 22]
 [43 24 88 33]]
[[ 1  2  4 33]
 [ 1  9 13 61]
 [22 24 43 88]]


In [131]:
import numpy as np
# Define structured array data type
dtype1 = [
	('name', 'S10'),	# Fixed-length string (10 bytes)
	('height', float),  # Height as float
	('age', int),   	# Age as integer
	('gender', 'S10')   # Gender as string
]
# Data values
values = [
	('Shubham', 5.9, 23, 'M'),
	('Arpita', 5.6, 23, 'F'),
	('Vaishali', 5.2, 30, 'F')
]
# Create structured array
x = np.array(values, dtype=dtype1)
print("Original array:")
print(x)

# Sort by age
y = np.sort(x, order='age')
print("\nSorted by age:")
print(y)
# Sort by age, then height
z = np.sort(x, order=['age', 'height'])
print("\nSorted by age, then height:")
print(z)



Original array:
[(b'Shubham', 5.9, 23, b'M') (b'Arpita', 5.6, 23, b'F')
 (b'Vaishali', 5.2, 30, b'F')]

Sorted by age:
[(b'Arpita', 5.6, 23, b'F') (b'Shubham', 5.9, 23, b'M')
 (b'Vaishali', 5.2, 30, b'F')]

Sorted by age, then height:
[(b'Arpita', 5.6, 23, b'F') (b'Shubham', 5.9, 23, b'M')
 (b'Vaishali', 5.2, 30, b'F')]


In [132]:
a = "How you doing?"
y = np.char.split(a)
print(y)


['How', 'you', 'doing?']


In [138]:
x = "We, very happily, welcome you all!"
out = np.char.split(x, sep=',', maxsplit=3)
print(out)


['We', ' very happily', ' welcome you all!']


In [140]:
inp = np.array(['Apple', 'Python', 'NumPy', 'StudyTonight'])
sep = np.array(['***'])
output = np.char.join(sep, inp)
print(output)


['A***p***p***l***e' 'P***y***t***h***o***n' 'N***u***m***P***y'
 'S***t***u***d***y***T***o***n***i***g***h***t']


In [142]:
a = np.char.join(':', 'MakeupArtist')
print(a)


M:a:k:e:u:p:A:r:t:i:s:t
